// ─── Fallback Data (used when DB tables are empty) ──────────────────────────

export const fallbackStats = [
  {
    id: "1",
    icon: "❄️",
    value: "50,000+",
    label: "Tons Stored Monthly",
    description: "Kapasitas penyimpanan dingin aktif per bulan di seluruh klien kami",
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    icon: "🏭",
    value: "200+",
    label: "Industrial Clients",
    description: "Perusahaan industri pangan & logistik yang mempercayai solusi kami",
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    icon: "⚡",
    value: "99.8%",
    label: "Uptime Guarantee",
    description: "Rata-rata uptime sistem pendingin yang terpasang di seluruh lokasi",
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    icon: "🏆",
    value: "15+",
    label: "Years of Excellence",
    description: "Pengalaman lebih dari satu dekade di industri cold chain Indonesia",
    order: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const fallbackTestimonials = [
  {
    id: "1",
    text: "PT AFT menyelesaikan masalah spoilage kami secara total. Uptime rock solid, tim support sangat responsif 24/7. Sangat recommended untuk kebutuhan cold storage serius.",
    author: "Budi Santoso",
    company: "PT Distributor Daging Nusantara",
    rating: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    text: "Instalasi selesai tepat waktu dalam 7 hari seperti yang dijanjikan. Kualitas mesin sangat premium dan efisiensi energinya jauh lebih baik dari vendor sebelumnya.",
    author: "Sari Wijayanti",
    company: "Cold Chain Indonesia Tbk",
    rating: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    text: "ROI tercapai lebih cepat dari perkiraan kami — hanya 16 bulan. Sistem monitoring real-time sangat membantu operasional gudang kami yang berjalan 24 jam.",
    author: "Hendra Kurniawan",
    company: "PT Logistik Pro Sejahtera",
    rating: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    text: "Tim teknis mereka sangat kompeten dan profesional. Konsultasi awal sangat membantu kami memilih kapasitas yang tepat tanpa over-budget.",
    author: "Dian Pertiwi",
    company: "Supermarket Fresh Mart",
    rating: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    text: "Garansi seumur hidup bukan gimmick — sudah 3 tahun pakai dan mereka benar-benar handle setiap maintenance tanpa biaya tambahan. Luar biasa.",
    author: "Agus Prasetyo",
    company: "PT Mitra Boga Utama",
    rating: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    text: "Dari sisi compliance, semua sertifikasi ISO sudah terpenuhi. Audit BPOM berjalan lancar karena sistem suhu kami terdokumentasi dengan sangat baik.",
    author: "Ratna Dewi",
    company: "Food Manufacturing Indonesia",
    rating: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const fallbackFAQs = [
  {
    id: "1",
    question: "Berapa kapasitas cold room yang bisa di-custom?",
    answer: "Kami menyediakan solusi cold room dari kapasitas 5 ton hingga 500+ ton per unit. Untuk kebutuhan di atas 500 ton, kami menawarkan sistem modular yang dapat dikombinasikan. Setiap proyek melalui site survey gratis untuk menentukan spesifikasi optimal.",
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    question: "Berapa lama garansi produk yang diberikan?",
    answer: "Semua unit kami dilengkapi lifetime warranty untuk komponen utama (kompresor, evaporator, kondenser). Garansi ini mencakup suku cadang dan jasa teknisi tanpa biaya tambahan selama masa garansi berlaku. Garansi workmanship instalasi adalah 2 tahun.",
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    question: "Bagaimana sistem monitoring real-time bekerja?",
    answer: "Sistem IoT kami memungkinkan Anda memantau suhu, humidity, dan status kompressor secara real-time melalui dashboard web maupun aplikasi mobile. Alert otomatis akan dikirim via WhatsApp & email jika ada parameter yang di luar batas yang ditetapkan.",
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    question: "Berapa lama proses instalasi berlangsung?",
    answer: "Standar setup cold room kami memakan waktu 7 hari kerja untuk ukuran hingga 100 ton. Proyek berskala lebih besar (100–500 ton) memerlukan 14–21 hari. Jadwal instalasi disesuaikan agar tidak mengganggu operasional bisnis Anda yang sudah berjalan.",
    order: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    question: "Apakah ada biaya tersembunyi (hidden fees)?",
    answer: "Tidak ada. Semua biaya tercantum secara transparan dalam proposal yang kami berikan — termasuk biaya material, jasa instalasi, dan commissioning. Tidak ada biaya kejutan setelah proyek berjalan. Kami juga menawarkan opsi leasing & cicilan untuk kemudahan cash flow.",
    order: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    question: "Tim support tersedia jam berapa?",
    answer: "Tim support kami tersedia 24/7 termasuk weekend dan hari libur nasional. Anda dapat menghubungi kami melalui hotline, WhatsApp, atau tiket di dashboard monitoring. Response time darurat kami adalah maksimal 2 jam untuk area Jabodetabek, 4 jam untuk kota lainnya.",
    order: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    question: "Apakah bisa custom ukuran atau desain cold room?",
    answer: "Ya, kami sangat welcome custom requirements. Tim engineer kami akan melakukan assessment dan membuat desain 3D sebelum proses fabrikasi dimulai. Kami juga mengerjakan proyek retrofit — upgrade atau ekspansi cold room yang sudah ada tanpa harus bongkar total.",
    order: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    question: "Berapa estimasi ROI (Return on Investment)?",
    answer: "Rata-rata klien kami mencapai ROI dalam 18–24 bulan melalui kombinasi pengurangan spoilage, efisiensi energi 30–40% dibanding sistem lama, dan eliminasi downtime. Kami menyediakan ROI calculator gratis sebagai bagian dari proposal konsultasi.",
    order: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const TRUSTED_CLIENTS = [
  { id: "1", name: "PT Mitra Boga", sector: "Food Manufacturing" },
  { id: "2", name: "Cold Chain Indonesia", sector: "Logistics" },
  { id: "3", name: "Logistics Pro", sector: "Supply Chain" },
  { id: "4", name: "Fresh Mart Group", sector: "Retail" },
  { id: "5", name: "Indo Seafood Corp", sector: "Seafood Processing" },
  { id: "6", name: "Agro Nusantara", sector: "Agriculture" },
  { id: "7", name: "Pharma Cold", sector: "Pharmaceutical" },
  { id: "8", name: "Bumi Protein", sector: "Meat Processing" },
  { id: "9", name: "Trans Fridge", sector: "Transportation" },
  { id: "10", name: "Inka Food", sector: "Frozen Food" },
];
